# Generated by Django 3.1 on 2021-04-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210403_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='libraries'),
        ),
    ]
