# Generated by Django 3.1 on 2021-04-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210403_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='source',
            field=models.CharField(blank=True, choices=[('user', 'User-submitted'), ('little-free-library', 'Little Free Library')], help_text='Data source of library', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='media/libraries'),
        ),
    ]
